version: '3'

services:
  web:
    build:
      context: .
      dockerfile: prototype_editor/Dockerfile

    env_file:
      - prototype_editor/.env
    command: bash -c "
      python insert_samples.py;
      uvicorn api_main:app
      --host 0.0.0.0 --port 8000
      --lifespan=on --use-colors 
      --reload
      "
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4.3
    env_file:
      - prototype_editor/.env
    ports:
      - "27017:27017"
    environment:
      - "MONGO_INITDB_DATABASE=${MONGO_DB}"
      - "MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}"
      - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}"
    command:
      mongod