# these are classes that cannot be changed once the node is specified
CYTO_LITERAL_NODE_CLASS = "CYTO_LITERAL_NODE_CLASS"
CYTO_MUTABLE_NODE_CLASS = "CYTO_MUTABLE_NODE_CLASS"
CYTO_MESSAGE_NODE_CLASS = "CYTO_MESSAGE_NODE_CLASS"
CYTO_MESSAGE_EDGE_CAN_EDIT_CLASS = "CYTO_MESSAGE_EDGE_CAN_EDIT_CLASS"

# these are classes controlled by client side callbacks
CYTO_MESSAGE_NODE_TMP_HIDE = "CYTO_MESSAGE_NODE_TMP_HIDE"
CYTO_MESSAGE_NODE_NAV_FOCUS = "CYTO_MESSAGE_NODE_NAV_FOCUS"
CYTO_MESSAGE_NODE_HAS_CHILD_TMP_HIDDEN = "CYTO_MESSAGE_NODE_HAS_CHILD_TMP_HIDDEN"

# these are classes controlled by server side callbacks
CYTO_PRESET_CLASS = "CYTO_PRESET_CLASS"
CYTO_PLACEHOLDER_CLASS = "CYTO_PLACEHOLDER_CLASS"
